# Makefile
demo: main.cpp
	g++ main.cpp -o demo -I /usr/local/lib -L /usr/local/lib  -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_objdetect -lopencv_bgsegm -lopencv_video -lopencv_calib3d
